// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using task_day_2_entityf_ramework;

#nullable disable

namespace task_day_2_entityf_ramework.Migrations
{
    [DbContext(typeof(appdbcontent))]
    partial class appdbcontentModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("task_day_2_entityf_ramework.course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("description")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("VARCHAR");

                    b.Property<int>("durationInHours")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            description = "Learn the basics of C# programming language including variables, loops and OOP concepts.",
                            durationInHours = 30,
                            name = "C# Fundamentals"
                        },
                        new
                        {
                            Id = 2,
                            description = "Build modern web applications and APIs using ASP.NET Core framework.",
                            durationInHours = 40,
                            name = "ASP.NET Core"
                        },
                        new
                        {
                            Id = 3,
                            description = "Master Code First approach, migrations, relationships and querying with EF Core.",
                            durationInHours = 25,
                            name = "Entity Framework Core"
                        },
                        new
                        {
                            Id = 4,
                            description = "Understand database design, T-SQL queries, joins and stored procedures.",
                            durationInHours = 20,
                            name = "SQL Server Basics"
                        },
                        new
                        {
                            Id = 5,
                            description = "Introduction to HTML, CSS and JavaScript for building interactive websites.",
                            durationInHours = 35,
                            name = "Web Development"
                        });
                });

            modelBuilder.Entity("task_day_2_entityf_ramework.student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("age")
                        .HasColumnType("int");

                    b.Property<string>("fullname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<decimal>("percent")
                        .HasColumnType("decimal(4,2)");

                    b.HasKey("Id");

                    b.ToTable("Students", t =>
                        {
                            t.HasCheckConstraint("CK_Student_Age", "[Age] >= 16");

                            t.HasCheckConstraint("CK_Student_Email", "[Email] LIKE '%_@__%.__%'");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "shahd@gmail.com",
                            age = 20,
                            fullname = "shahd",
                            percent = 85m
                        },
                        new
                        {
                            Id = 2,
                            Email = "sara.ali@gmail.com",
                            age = 19,
                            fullname = "Sara Ali",
                            percent = 92m
                        },
                        new
                        {
                            Id = 3,
                            Email = "mariam.tarek@yahoo.com",
                            age = 22,
                            fullname = "mariam Tarek",
                            percent = 78m
                        },
                        new
                        {
                            Id = 4,
                            Email = "nour.hassan@outlook.com",
                            age = 18,
                            fullname = "Nour Hassan",
                            percent = 88m
                        },
                        new
                        {
                            Id = 5,
                            Email = "katy.adel@gmail.com",
                            age = 21,
                            fullname = " katy Adel",
                            percent = 65m
                        },
                        new
                        {
                            Id = 6,
                            Email = "shahd@gmail.com",
                            age = 20,
                            fullname = "shahd",
                            percent = 85m
                        },
                        new
                        {
                            Id = 7,
                            Email = "sara.ali@gmail.com",
                            age = 19,
                            fullname = "Sara Ali",
                            percent = 92m
                        },
                        new
                        {
                            Id = 8,
                            Email = "mariam.tarek@yahoo.com",
                            age = 22,
                            fullname = "mariam Tarek",
                            percent = 78m
                        },
                        new
                        {
                            Id = 9,
                            Email = "nour.hassan@outlook.com",
                            age = 18,
                            fullname = "Nour Hassan",
                            percent = 88m
                        },
                        new
                        {
                            Id = 10,
                            Email = "hana.sameh@yahoo.com",
                            age = 16,
                            fullname = "Hana Sameh",
                            percent = 82m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
